name: CD
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSHPASS: ${{ secrets.APP_PASS }}

    steps:
      - uses: actions/checkout@v2

      - name: APT UPDATE and INSTALL SSHPASS
        run:
          sudo apt update && sudo apt install sshpass
      
      - name: test pwd
        run:
          sshpass -e ssh -A -o stricthostkeychecking=no ${{ secrets.APP_USER }}@${{ secrets.APP_HOST }}
          "cd sites/sylius-test.valentin-moreau.com &&
          git pull &&
          php bin/console doctrine:migrations:migrate --no-interaction &&
          php bin/console sylius:theme:assets:install &&
          nvm use v16.19.1 &&
          npm run build:prod &&
          php bin/console cache:clear --env=prod"
